create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.app_departments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  full_name text not null,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin', 'manager', 'employee')),
  department_id bigint references public.app_departments(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  priority text not null check (priority in ('Low', 'Medium', 'High', 'Critical')),
  status text not null check (status in ('To Do', 'In Progress', 'Done')),
  due_date date not null,
  assigned_to bigint not null references public.app_users(id) on delete restrict,
  department_id bigint references public.app_departments(id) on delete set null,
  created_by bigint references public.app_users(id) on delete set null,
  updated_by bigint references public.app_users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.app_activity_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references public.app_users(id) on delete set null,
  affected_user_id bigint references public.app_users(id) on delete set null,
  task_id bigint references public.app_tasks(id) on delete set null,
  actor_name text not null default 'System',
  task_title text,
  action text not null,
  details text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_app_users_role on public.app_users(role);
create index if not exists idx_app_users_department_id on public.app_users(department_id);
create index if not exists idx_app_tasks_assigned_to on public.app_tasks(assigned_to);
create index if not exists idx_app_tasks_department_id on public.app_tasks(department_id);
create index if not exists idx_app_tasks_due_date on public.app_tasks(due_date);
create index if not exists idx_app_activity_logs_created_at on public.app_activity_logs(created_at desc);
create index if not exists idx_app_activity_logs_affected_user_id on public.app_activity_logs(affected_user_id);

drop trigger if exists app_departments_set_updated_at on public.app_departments;
create trigger app_departments_set_updated_at
before update on public.app_departments
for each row
execute function public.set_updated_at();

drop trigger if exists app_users_set_updated_at on public.app_users;
create trigger app_users_set_updated_at
before update on public.app_users
for each row
execute function public.set_updated_at();

drop trigger if exists app_tasks_set_updated_at on public.app_tasks;
create trigger app_tasks_set_updated_at
before update on public.app_tasks
for each row
execute function public.set_updated_at();

insert into public.app_departments (name, description)
values
  ('Operations', 'Delivery, operations, and support workstreams.'),
  ('Engineering', 'Product, engineering, and technical execution.'),
  ('Finance', 'Budgeting, approvals, and commercial oversight.'),
  ('People', 'Hiring, onboarding, and employee experience.')
on conflict (name) do nothing;

insert into public.app_users (
  full_name,
  username,
  password_hash,
  role,
  department_id,
  is_active
)
select
  'System Administrator',
  'admin',
  '$2b$10$aNaF8jSRUGMFnORthGTqie5JfDzMluAMxxWvJeZIQxf1wKVSuUoK.',
  'admin',
  d.id,
  true
from public.app_departments d
where d.name = 'Operations'
  and not exists (
    select 1
    from public.app_users u
    where u.username = 'admin'
  );
